### ISSUE TITLE
take advantage of empty base class optimization

### ISSUE THREAD

**Issue by nikhedonia** [LoopPerfect/valuable#2]

**Comment by KubaO** [comment]
That optimization is pretty much automatically taken care of - anyone inheriting from `DefaultCloner` will not pay a penalty for `DefaultCloner` being empty. Since you store the empty `cloner` in `value_ptr<T, DefaultCloner>`, there isn't much you can do other than either providing a partial specialization that doesn't include the `cloner`, or deriving from a cloner-less base class.

**Comment by KubaO** [comment]
Never mind, this is a good idea and involves privately deriving from Cloner.
